### ISSUE TITLE
build dependencies

### ISSUE THREAD

**Issue by GitMensch** [compiler-explorer/cobol-builder#1]
If the resulting COBOL environments should build with JSON and XML support you'd likely want to add libjson-c-dev and libxml2-dev.

Note: When building GnuCOBOL (only) you should not need autoconf; bzip2 and xz-utils only if you want those archive formats.

**Comment by mattgodbolt** [comment]
I required autoconf else the "./autogen.sh" I copied from the infra pull request complains about a missing autoconf.

bzip2 and xz-utils are required to uncompress the source archive and compress the resulting binaries.

I'll add libjson-c-dev and libxml2-dev if those are required to make a useful COBOL. I have no opinions myself, just finding the minimum requirements.

**Comment by mattgodbolt** [comment]
With those packages, the local build I just tested:
```
configure:  Dynamic loading:                             System
configure:  Use gettext for international messages:      yes
configure:  Use fcntl for file locking:                  yes
configure:  Use math multiple precision library:         gmp
configure:  screen I/O (no curses found):                NO
configure:  Use Berkeley DB for INDEXED I/O:             yes
configure:  Used for XML I/O:                            libxml2
configure:  Used for JSON I/O:                           json-c
```

**Comment by mattgodbolt** [comment]
(let me know if I'm building it wrong though please! I'm literally copy pasting from the https://github.com/compiler-explorer/infra/pull/951/files to get the autogen.sh)

Also in most other builds we use `git` or similar to grab tagged source, which then lets us pick up a "trunk" build that we then compile daily. If that's useful, let me know where best to pick up the latest code.

**Comment by GitMensch** [comment]
> I required autoconf else the "./autogen.sh" I copied from the infra pull request complains about a missing autoconf.

Ah, if you use any release tarball (even nightly builds) you don't need autogen.sh, just start with `configure` (if there's no special need for a specific set of autotools for the build environment).

> Also in most other builds we use git or similar to grab tagged source, which then lets us pick up a "trunk" build that we then compile daily. If that's useful, let me know where best to pick up the latest code.

That's of course very different (I wouldn't do it for released builds where a tarball is often best, because that's what most people would use on their environment and also what the distros use).
For "working code" (which then should be a separate version) it would be reasonable to pick via `svn` - because there's no official git mirror.

In this I'd suggest to pick both development versions `https://svn.code.sf.net/p/gnucobol/code/branches/gnucobol-3.x` and `https://svn.code.sf.net/p/gnucobol/code/trunk` (trunk misses a bunch of 3.x where latest bugfixes for the 3.x release line currently go to, they will take some weeks to get into trunk where the work on "the next big things" is done) - and with those you'd need to start with autogen.sh (but also include bison, flex and -if you don't fake it by `touch` also help2man and texinfo).
... 
Note: there is a semi-semi-official github mirror which is up-to-date, currently at https://github.com/OCamlPro/gnucobol3/, likely will be moved to https://github.com/OCamlPro/gnucobol (which also has automated updates) - i both cases "trunk=master".

For ncurses - I don't think that the godbolt page will use them (does it) so better keep it explicit disabled then.

**Comment by mattgodbolt** [comment]
If it's not a big deal then I'll stick with unpacking the pre-built named versions (and remove autotools). If we ever want to support daily builds, we can revisit. Thanks!

**Comment by mattgodbolt** [comment]
I'm now hitting issues with shared library paths. I'm installing with:

```
make prefix=${STAGING_DIR} install
```

it seems there's no `rpath` or similar set on the executables, testing from a staging dir:

```
# ldd /root/staging/bin/cobc
	linux-vdso.so.1 (0x00007ffda54e3000)
	libcob.so.4 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4d679bd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4d67d1f000)
```

Any thoughts on how to handle this? We build in one location and then assume we can move it elsewhere. Will I have to use elfedit or similar to add a `$ORIGIN/../lib` rpath?

**Comment by GitMensch** [comment]
> Any thoughts on how to handle this? We build in one location and then assume we can move it elsewhere. Will I have to use elfedit or similar to add a `$ORIGIN/../lib` rpath?

What about `LDFLAGS='-Wl,-rpath,$ORIGIN/../lib'` passed to configure? Note that this will also "leak" into generated COBOL modules which is _possibly_ not what you want. `PROGRAMS_LIBS` could be used instead, but this isn't available in old GnuCOBOL versions.

In any case: If you want to move the libraries you may need to pass the path to libcob as part of the cobc invocation later, too...

... or, easiest solution for running: `export LD_LIBRARY_PATH` on the install site.

**Comment by mattgodbolt** [comment]
Yeah I'm just trying out the LDFLAGS trick now :) will keep you posted...

> ... or, easiest solution for running: export LD_LIBRARY_PATH on the install site.

not the easiest when we have 1000 ish compilers running on a fleet of ephemeral computers... which is why we like to make it so the binaries "just work" wherever they end up coming from :)

**Comment by mattgodbolt** [comment]
and inevitably, something in the various layers of `make` loses it. this from `env 'LDFLAGS=-Wl,-rpath,$ORIGIN/../lib' ./build.sh 3.2-rc2 /tmp` - fun and games trying to find the right number of escapes...

```
 0x000000000000001d (RUNPATH)            Library runpath: [RIGIN/../lib]
```

**Comment by mattgodbolt** [comment]
https://stackoverflow.com/questions/37060747/escaping-origin-for-libtool-based-project hahah not the first to find this out...

**Comment by GitMensch** [comment]
> and inevitably, something in the various layers of `make` loses it. this from `env 'LDFLAGS=-Wl,-rpath,$ORIGIN/../lib' ./build.sh 3.2-rc2 /tmp`

Note: it is always preferable to specify LDFLAGS (or any other flags configure picks up) in the configure line (after the options), instead in the environment.

**Comment by mattgodbolt** [comment]
Great point: thanks!

**Comment by mattgodbolt** [comment]
```
./configure LDFLAGS="-Wl,-rpath,'\$\$ORIGIN/../lib'"
```
worked...

**Comment by GitMensch** [comment]
The interesting question now is if this still works when using that from a different install place with the compile and link phase of COBOL modules from cobc (the generated C files include a header from the installed place and link against the installed library); if it doesn't work you'd have to either auto-add `-I / path/to/this/include -L /path/to/this/lib -Q '-Wl,-rpath,path/to/this/lib'` to the used cobc options (either directly or via environment variables - see `cobc --info` to get a clue which ones you could set).

**Comment by mattgodbolt** [comment]
Thanks; I'll check on that shortly...

**Comment by mattgodbolt** [comment]
> -I / path/to/this/include -L /path/to/this/lib -Q '-Wl,-rpath,path/to/this/lib' to the used cobc options

that seems an unfortunate thing to have to do...let's hope not...

**Comment by mattgodbolt** [comment]
ok latest building now at ... https://github.com/compiler-explorer/infra/actions/runs/4333430696

**Comment by GitMensch** [comment]
> > -I /path/to/this/include -L /path/to/this/lib -Q '-Wl,-rpath,path/to/this/lib' to the used cobc options
> 
> that seems an unfortunate thing to have to do...let's hope not...

You likely know, but If that's the case and you don't know the install dir from the outside you could get "part to this" via `dirname $(dirname $(which cobc))..` from within the runner.

**Comment by mattgodbolt** [comment]
Thanks. We do know the install directory (we're aware when we run it). `which cobc` wouldn't find `cobc` in this instance, we will be running `cobc` with a fully qualified pathname (and it won't be on the `PATH`, which I hope isn't a problem)

**Comment by mattgodbolt** [comment]
ok next problem:
```
/opt/compiler-explorer/cobol/gcc-3.2-rc2/bin/cobc: error while loading shared libraries: libjson-c.so.4: cannot open shared object file: No such file or directory
```

there are runtime dependencies on those installed libraries...

Unfortunately I'm running out of time here and will have to look into this tomorrow.

For our needs; we need to be able to run a compiler somewhat "hermetically": that is, the installation directory (which can be anywhere on the machine) needs to contain all that's needed to run the compiler, minus libc and kernel libraries.  So far we've managed to get by with this for all the other compilers we use. We can probably "just" copy the required libraries into the `lib` directory of the install, but we're into a world of "but what if those libraries need libraries" etc etc.

One thought is to statically link those, if it's an option?

As you might appreciate our requirements are somewhat unusual given our setup: we can't have all these things as system installations as we need to support nearly 2,000 different compilers and their oddities!

**Comment by mattgodbolt** [comment]
At a push - I guess - we could add these runtime dependencies to our base image. but that's a pretty huge effort involving upgrading the base VM used on the whole site (and doesn't scale all that well...) It's there if we have to though!

**Comment by mattgodbolt** [comment]
fwiw the full `ldd` is:
```
root@ef4b285b2a02:~# ldd /root/staging/bin/cobc
	linux-vdso.so.1 (0x00007ffe37ba1000)
	libcob.so.4 => /root/staging/bin/../lib/libcob.so.4 (0x00007f8299b93000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f829999d000)
	libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f8299919000)
	libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f829975f000)
	libjson-c.so.4 => /lib/x86_64-linux-gnu/libjson-c.so.4 (0x00007f829974d000)
	libdb-5.3.so => /lib/x86_64-linux-gnu/libdb-5.3.so (0x00007f829959e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8299596000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8299d7a000)
	libicuuc.so.66 => /lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007f82993b0000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8299394000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f829936b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f829921c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f82991f9000)
	libicudata.so.66 => /lib/x86_64-linux-gnu/libicudata.so.66 (0x00007f8297736000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8297554000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8297539000)
```

**Comment by mattgodbolt** [comment]
Running on our actual production machines...

**Comment by GitMensch** [comment]
I see - not being in PATH is totally fine (but I'm quite sure you will need to either pass all those options along to the `cobc` invocation or check once which options it uses (see `COB_CFLAGS` and `COB_LIBS` in `cobc --info`) and set them inline adjusting the old install-path by the new.

> there are runtime dependencies on those installed libraries...

Of course, as those are used at runtime to provide the support for XML, JSON and `ORGANIZATION INDEXED`.

I _guess_ you have most of that in your base image... which is what your last ldd says it is, right?

**Comment by mattgodbolt** [comment]
That `ldd` was on my local machine. I'm going to run on a production image now... please hold :)

**Comment by mattgodbolt** [comment]
well, amazingly we have an interesting issue:

```
$ ldd /opt/compiler-explorer/cobol/gnucobol-3.2-rc2/bin/cobc
        linux-vdso.so.1 (0x00007ffc87224000)
        libcob.so.4 => /opt/compiler-explorer/cobol/gnucobol-3.2-rc2/bin/../lib/libcob.so.4 (0x00007fa18f260000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa18f05d000)
        libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fa18efd9000)
        libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fa18ee1f000)
        libjson-c.so.4 => /lib/x86_64-linux-gnu/libjson-c.so.4 (0x00007fa18ee0d000)
        libdb-5.3.so => /lib/x86_64-linux-gnu/libdb-5.3.so (0x00007fa18ec5c000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa18ec56000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa18f447000)
        libicuuc.so.66 => /lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007fa18ea70000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa18ea54000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fa18ea2b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa18e8dc000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa18e8b7000)
        libicudata.so.66 => /lib/x86_64-linux-gnu/libicudata.so.66 (0x00007fa18cdf6000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa18cc14000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa18cbf9000)
```
in fact 
```
ubuntu@ip-172-30-1-12:~$ /opt/compiler-explorer/cobol/gnucobol-3.2-rc2/bin/cobc --info
cobc (GnuCOBOL) 3.2-rc2.0
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Keisuke Nishida, Roger While, Ron Norman, Simon Sobisch, Edward Hart
Built     Mar 05 2023 00:00:06
Packaged  Feb 11 2023 01:47:30 UTC
C version "9.4.0"

build information
build environment        : x86_64-pc-linux-gnu
CC                       : gcc
C version                : "9.4.0"
CPPFLAGS                 : 
CFLAGS                   : -O2 -pipe -finline-functions -fsigned-char
                           -Wall -Wwrite-strings -Wmissing-prototypes
                           -Wno-format-y2k
LD                       : /usr/bin/ld
LDFLAGS                  : -Wl,-rpath,'$$ORIGIN/../lib'
                           -Wl,-z,relro,-z,now,-O1

GnuCOBOL information
COB_CC                   : gcc
COB_CFLAGS               : -pipe -I/usr/local/include -Wno-unused
                           -fsigned-char -Wno-pointer-sign
COB_DEBUG_FLAGS          : -ggdb3 -fasynchronous-unwind-tables
COB_LDFLAGS              : -Wl,-rpath,$$ORIGIN/../lib
COB_LIBS                 : -L/usr/local/lib -lcob
COB_CONFIG_DIR           : /usr/local/share/gnucobol/config
COB_COPY_DIR             : /usr/local/share/gnucobol/copy
COB_MSG_FORMAT           : GCC
COB_OBJECT_EXT           : o
COB_MODULE_EXT           : so
COB_EXE_EXT              : 
64bit-mode               : yes
BINARY-C-LONG            : 8 bytes
endianness               : little-endian
native EBCDIC            : no
extended screen I/O      : disabled
variable file format     : 0
sequential file handler  : built-in
indexed file handler     : BDB
mathematical library     : GMP
XML library              : libxml2
JSON library             : json-c
```

**Comment by mattgodbolt** [comment]
so - our administration system can't install it (as part of the install is to run the program to ensure it works, and if it doesn't it rejects...). But by (happy!?) coincidence we already have those libraries on our image. I'll update our admin installer so it is OK with things and then I need to pause.

**Comment by mattgodbolt** [comment]
Well, I checked it in, but unfortunately I can't update our admin installer: it's a different OS and thus can't run libjson-c-4 (it has only v5 available). I need to bail, but this is one of the reasons we try and build things as sealed as possible (it becomes a nightmare to update OSes if you need to rebuild ~3TB of compilers and libraries...)

**Comment by GitMensch** [comment]
Sorry - I've actually was so in "common users' support mode" that I've forgot that there will be no running of the generated sources!

Then definitely change `--with-db --with-json=json-c` to `--without-db --without-json` - the compiler wont use that at all.
And as libxml2 (via libob which links that in) is only used in the compiler to verify uris "in depth" instead of "in general" I'd likely go with `--without-xml2`, too.... and drop those dependencies from the builder.
... and if there's no hidden LANG setting I've missed and if it isn't planned to be added to gotbolt also add `--disable-nls`.

Note: This will make the cobc binary executable on the runner (it otherwise only gets in GMP, which you likely have with a matching version and libc and possibly libm), to make it actually _working_ you'd need to use one of the following approaches:

1) use a wrapper for cobc which first sets  `COB_CONFIG_DIR` and `COB_COPY_DIR` and passes `-I` to the appropriate place where the libcob.h for that installed version is (in your example `-I /opt/compiler-explorer/cobol/gnucobol-3.2-rc2/include`).
or
2) if it would be always installed in `/opt/compiler-explorer/cobol/gnucobol-3.2-rc2` (or another fixed path) change the `configure` invocation in the builder to use `--prefix=/opt/compiler-explorer/cobol/gnucobol-3.2-rc2`  and everything will just work out of the box

**Comment by GitMensch** [comment]
Suggested changes done with https://github.com/compiler-explorer/cobol-builder/pull/3; still open is the question: do we know the final "target" directory during building? If yes then we can fix the problems we otherwise need to tackle when running the compiler by just adding `--prefix`, as noted in the commit discussion.
